# -*- coding: utf-8 -*-
"""Paraphraser.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZXWZwrKJ9QxKgnA4-rV5EY9d6zG1FLOB
"""

# ! pip install git+https://github.com/PrithivirajDamodaran/Parrot.git

# Import libraries
from parrot import Parrot
import torch
import warnings
warnings.filterwarnings("ignore")

# For reproducibility
def random_state(seed):
  torch.manual_seed(seed)
  if torch.cuda.is_available():
    torch.cuda.manual_seed_all(seed)

random_state(1234)

#Init models (make sure you init ONLY once if you integrate this to your code)
parrot = Parrot(model_tag="prithivida/parrot_paraphraser_on_T5", use_gpu=False)
